# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabshare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cab',
            old_name='source',
            new_name='cab_source',
        ),
    ]
