# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabshare', '0002_auto_20171010_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cab',
            old_name='cab_source',
            new_name='source',
        ),
    ]
